From ubuntu:latest
WORKDIR /usr/local/bin
RUN apt-get -y update && apt-get -y install curl
RUN curl -L https://yt-dl.org/downloads/latest/youtube-dl -o /usr/local/bin/youtube-dl
RUN chmod a+rx /usr/local/bin/youtube-dl
CMD [ "youtube-dl","-cit" ]