version: '3'
services:
  db: kartoza/postgis:latest
   expose:5432
    environment: 
       - USERNAME=edwin
       - PASS=@edwinpg_data
    restart: on-failure:5
  pgadmin: crunchydata/crunchy-pgadmin4:centos7-10.5-2.1.0
    ports:
      -"0.0.0.0:5050"
    enviroment:
      - PGADMIN_SETUP_EMAIL=edwinkamaumuraya0@gmail.com
      - PGADMIN_SETUP_PASSWORD=@edwinpg_data
      - SERVER_PORT=5050

     